In [ ]:
import numpy as np

**Задание 1**

In [ ]:
reciepe = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=int, skiprows=1)
print(f'Первые 5 строк массива:\n{reciepe[:5]}')

Первые 5 строк массива:
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


**Задание 2**

In [ ]:
max_arr = np.max(reciepe, axis=0)
min_arr = np.min(reciepe, axis=0)
mean_arr = np.mean(reciepe, axis=0)
median_arr = np.median(reciepe, axis=0)

In [ ]:
print(f"Спеднее по столбцу minutes: {mean_arr[1]}")
print(f"Минимум по стобцу minutes: {min_arr[1]}")
print(f"Максимум по стобцу minutes: {max_arr[1]}")
print(f"Медиана по стобцу minutes: {median_arr[1]}")

Спеднее по столбцу minutes: 21601.00169
Минимум по стобцу minutes: 0
Максимум по стобцу minutes: 2147483647
Медиана по стобцу minutes: 40.0


In [ ]:
print(f"Спеднее по столбцу n_ingredients: {mean_arr[2]}")
print(f"Минимум по стобцу n_ingredients: {min_arr[2]}")
print(f"Максимум по столбцу n_ingredients: {max_arr[2]}")
print(f"Медиана по стобцу n_ingredients: {median_arr[2]}")

Спеднее по столбцу n_ingredients: 9.05528
Минимум по стобцу n_ingredients: 1
Максимум по столбцу n_ingredients: 39
Медиана по стобцу n_ingredients: 9.0


**Задание 3**

In [ ]:
qnt = np.quantile(reciepe, 0.75, axis=0)

# До ограниничения значения продолжительности
reciepe[reciepe[:, 1] > qnt[1]]

array([[280968,     85,     11],
       [ 99836,    180,      7],
       [ 87775,     80,     13],
       ...,
       [147074,     95,     15],
       [287943,     85,     15],
       [ 81993,    140,     14]])

In [ ]:
more_than_qnt = reciepe[reciepe[:, 1] > qnt[1]]
more_than_qnt[:, 1] = qnt[1]
reciepe[reciepe[:, 1] > qnt[1]] = more_than_qnt
print(f'Квантиль: {qnt[1]}')

# После ограничения значения продолжительности значением квантиля
reciepe[reciepe[:, 1] > qnt[1]]

Квантиль: 65.0


array([], shape=(0, 3), dtype=int64)

**Задание 4**

In [ ]:
count_zero_min = len(reciepe[reciepe[:, 1] == 0])
print(f'Рецепты для которых продолжительность равна 0: {count_zero_min}')

Рецепты для которых продолжительность равна 0: 479


In [ ]:
zero_min = reciepe[reciepe[:, 1] == 0]
zero_min[:, 1] = 1
reciepe[reciepe[:, 1] == 0] = zero_min
reciepe[reciepe[:, 1] == 0]

array([], shape=(0, 3), dtype=int64)

**Задание 5**

In [ ]:
unique_reciepe = np.unique(reciepe[:, 0])
len(unique_reciepe)

100000

**Задание 6**

In [ ]:
unique_ingredients = np.unique(reciepe[:, 2])
print(f'Значения количества ингридиентов: {unique_ingredients}')
print(f'Количество различных значений: {len(unique_ingredients)}')

Значения количества ингридиентов: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
Количество различных значений: 37


**Задание 7**

In [ ]:
five_and_less = reciepe[reciepe[:, 2] <= 5].copy()
five_and_less

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

**Задание 8**

In [ ]:
ing_per_min = reciepe[:, 2] / reciepe[:, 1]
print(f'Ингридиентов / мин для каждого рецепта: {ing_per_min}')
max_ing_per_min = max(ing_per_min)
print(f'Максимальное количество ингридиентов в минуту: {max_ing_per_min}')

Ингридиентов / мин для каждого рецепта: [0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
Максимальное количество ингридиентов в минуту: 24.0


**Задание 9**

In [ ]:
top100 = reciepe[reciepe[:, 1].argsort()][:-101:-1]
mean_ing = np.mean(top100, axis=0)[2]
print(f'Среднее количество ингридиентов {mean_ing}')

Среднее количество ингридиентов 6.61


**Задание 10**

In [ ]:
random_idx = np.random.randint(len(reciepe), size=(1, 11))
reciepe[random_idx]

array([[[  1075,     75,      9],
        [117808,     30,     13],
        [527462,     25,      4],
        [158791,     65,     14],
        [159827,     22,      5],
        [ 94691,     60,     15],
        [355770,    155,      3],
        [279217,     50,     12],
        [199604,     15,     13],
        [111971,     25,     14],
        [306719,     10,     11]]])

**Задание 11**

In [ ]:
mean_ing = np.mean(reciepe, axis=0)[2]
count_less_mean = np.count_nonzero(reciepe[:, 2] < mean_ing)
res = 100 * count_less_mean / len(reciepe)
print(f'Процент рецептов, кол-во ингредиентов в которых меньше среднего: {res}%')

Процент рецептов, кол-во ингредиентов в которых меньше среднего: 58.802%


**Задание 12**

In [ ]:
easy_or_not = np.where((reciepe[:, 1] <= 20) & (reciepe[:, 2] <= 5) == True, 1, 0)
reciepe1 = np.concatenate((reciepe, easy_or_not[:, np.newaxis]), axis=1)
reciepe1

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

**Задание 13**

In [ ]:
count_easy = np.count_nonzero(reciepe1[:, 3] == 1)
res = 100 * count_easy / len(reciepe1)
print(f'Процент простых рецептов: {res}%')

Процент простых рецептов: 9.552%


**Задание 14**

In [ ]:
short = reciepe[reciepe[:, 1] < 10]
stand = reciepe[(10 <= reciepe[:, 1]) & (reciepe[:, 1] < 20)]
long = reciepe[20 <= reciepe[:, 1]]

rec_num = min(len(short), len(stand), len(long))

reciepe_3d = np.zeros((3, rec_num, 3), dtype=int)
reciepe_3d[0] = short[:rec_num]
reciepe_3d[1] = stand[:rec_num]
reciepe_3d[2] = long[:rec_num]
reciepe_3d

array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      1,      9],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [  9831,     15,      7],
        [335859,     12,     14],
        [256812,     10,      3]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]])